<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCoreHero.Results" Version="1.1.1" />
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
    <PackageReference Include="AspNetCoreHero.ThrowR" Version="1.0.0" />
    <PackageReference Include="FluentValidation" Version="9.3.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="9.3.0" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LanceCoffeeSystem.Domain\LanceCoffeeSystem.Domain.csproj" />
  </ItemGroup>
</Project>
